- name: SVC Control Automation Started
  hosts: localhost
  tasks:
    - name: Import SVC Control Task
      shell: |
        echo "whitefang test"
- name: Include a playbook from a collection
  ansible.builtin.import_playbook: ./tasks/svc_control.yml