---
- hosts: all
  vars:
   packages:
   - docker.io
   - kubeadm
   - kubectl
   - kubelet
  tasks:
  - name: Removing Repo File of Kubernetes.
    file:
     path: /etc/apt/sources.list.d/kubernetes.list
     state: absent

  - name: Uninstalling kubernetes related packages
    apt:
     name: "{{ item }}"
     state: absent
    with_items: "{{ packages }}"

  - name: Removing required files
    file:
     path: "{{ item }}"
     state: absent
    with_items:
    - /etc/kubernetes/
    - /var/lib/etcd/
    - $HOME/.kube/

