- name: Continue Settings
  hosts: all
  tasks:
    - name: Update hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "18.218.137.41 k8smasternode"
        - "18.188.44.146 k8sworkernode"

    - name: Check if firewalld is installed
      command: systemctl list-unit-files | grep firewalld
      register: firewalld_installed
      ignore_errors: yes

    - name: Stop Firewalld
      command: systemctl stop firewalld
      when: firewalld_installed.rc == 0
      ignore_errors: yes

    - name: Disable Firewalld
      command: systemctl disable firewalld
      when: firewalld_installed.rc == 0
      ignore_errors: yes

