- name: SVC Control Automation Started
  hosts: masternode
  tasks:
    - name: Get kubelet Service Status
      ansible.builtin.systemd:
       name: kubelet
      register: status
    - name: Print The Kubelet Service Status
      ansible.builtin.debug:
       var: status.status.ActiveState
    - name: Run The Service If It Is Not Running
      ansible.builtin.systemd:
       name: kubelet
       state: started
      when: status.status.ActiveState != "active"