- name: SVC Restart Automation Started
  hosts: masternode
  tasks:
    - name: Check if Service Exists
      shell: | 
        exist=$(systemctl status {{service_name}})
      register: service_status
    - name: Print Status Of Service Exist
      debug:
        var: service_status
    