- name: SVC Restart Automation Started
  hosts: masternode
  tasks:
    - name: Check if Service Exists
      shell: | 
        exist=$(systemctl status {{service_name}} 2>&1)
        if [[ $exist == *"could not be found"* ]]; then
          echo "NO"
        else
          echo "HERE"
        fi
      register: service_status
    - name: Print Status Of Service Exist
      debug:
        msg: "Your Service Does not Exist-----> So Your Service Has Not Been Restarted"
      when: service_status.stdout == "NO"
    - name: Restart The Service
      ansible.builtin.systemd:
        state: restarted
        name: service_name
      when: service_status.stdout == "HERE"
    
