---
master_ip: 18.218.137.41
worker_ip: 18.188.44.146
repo_file: kubernetes.repo
initiate_file: initiate.sh
selinux: /etc/selinux/config
node_name1: k8smasternode
node_name2: k8sworkernode
host_file: /etc/hosts
