- name: Print The Cluster Name,Environment and URL Address
  ansible.builtin.debug:
    msg: "URL: {{ hostvars[item].url }} Cluster Name: {{ hostvars[item].cluster_name }}"

- name: Get NameSpace List With Api Call
  ansible.builtin.uri:
    url: "{{ hostvars[item].url }}/api/v1/namespaces/"
    method: GET
    body_format: json
    status_code: [200, 202]
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: "Bearer {{ hostvars[item].token }}"
    register: get_namespace
    with_items:
      - "{{ groups[ env ] }}"

- name: Print The NameSpace List
  ansible.builtin.debug:
    var: get_namespace

