---
- name: Install Kubernetes
  hosts: all
  gather_facts: true
  tasks:
    - name: Update package cache and install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Download Kubernetes repository key
      shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg add -

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
      become: yes

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Kubernetes packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubelet
        - kubeadm
        - kubectl

